### ISSUE TITLE
My pc broke

### ISSUE THREAD

**Issue by TheoHaines** [k3rn31p4nic/ZOD#1]
:(

**Comment by ghost** [comment]
well, it worked as intended lmao

**Comment by Ema-exe** [comment]
Worked

**Comment by FeltMacaroon389** [comment]
Sounds like a skill issue

**Comment by TCatFun** [comment]
dude you werent supposed to destroy your pc...
you probally need a new harddrive

**Comment by TCatFun** [comment]
or an entire new cpu and gpu...
idk

**Comment by Bobbeepbeep** [comment]
should of not extracted it
