### ISSUE TITLE
it's still working on windows?

### ISSUE THREAD

**Issue by ghost** [k3rn31p4nic/ZOD#4]
i read that the default windows extract function won't extract recursively an archive, and i don't use windows to test it

**Comment by ViSzKe** [comment]
It doesn't work on Windows for me, haven't tried with 7-zip yet

**Comment by HairlessGorilla123** [comment]
no it doesn't work on windows. extract it and you'll see.

**Comment by ghost** [comment]
> no it doesn't work on windows. extract it and you'll see.

sad but thank you for testing it!
